src/core/class.db.php
src/domain/tickets/repositories/class.tickets.php

Fixes the issue reported in #179 by introducing a simple new static function in `db` that will create a binding string for use in PDO queries with `IN` clauses, and in the tickets repository, iterating over the users filter array to match the binding string.

fix: use PDO injection for IN clause for tickets query for users filter

---

config/settings.php
public/index.php

With more digging it was found that ultimately the problem in #208 is in the mishandling of the configurable `$appUrl` variable. This variable is essentially ignored in the calls to `CURRENT_URL`. This problem could cause various other issues in the future. Here is a quick fix that was tested for my use case. I removed my "workaround" that I put in the mentioned issue, used port 80, and included the changes here. Feel free to suggest changes if needed.

use appUrl in CURRENT_URL

---

src/core/class.install.php

update was always possible - this fix will use a correct version comparision.
Before you compared 20104 with 214 - would never work 
Now you compare 20104 with 20104
And it throws the correct error now

FIX - FIx Update check for correct version

---

src/core/class.install.php

I'm new to PR, so I don't know if this is the right branch name and how to do it, but I had a problem with a new install, so I fixed it.
It seems that psettings is missing when initializing zp_projects.

FIX Fixed the problem of missing psettings when initializing zp_projects

---

gruntfile.js

a simple fix which adds default tinymce icons.
fixes #376

fix: add tinymce default icons to build sources. fixes #376

---

config/configuration.sample.php
public/backup.php
public/download.php
src/core/class.fileupload.php

This PR fixes and improves the handling of S3 storage servers, that are not on AWS S3.
**Changes:**
- fix configuration of s3EndPoint by ENV
- fix upload to S3 when folderName is empty
- allow path-style buckets instead of relying on default subdomain style. This adds new s3UsePathStyleEndpoint config variable and LEAN_S3_PATH_STYLE_ENDPOINT environment variable
A temporary docker image, which we use internally until these changes are releases, can be found on docker-hub: https://hub.docker.com/r/droidsolutions/leantime-s3-fix/tags

fix and improve S3 support for non-AWS S3 Servers like MINIO

---

src/domain/projects/services/class.projects.php

As a user I already know when I created/edited a ticket some moments ago, so a notifaction by mail should not be sent. 
Please feel free to comment if you have some thoughts about this change.

feat: ignore own account in email notifications to reduce mails

---

public/css/style.default.css

Show multiline if the "project name / project client" is too long.
Before:
After:

feat: make project multiselect multiline

---

src/domain/users/controllers/class.editUser.php

The `$_POST['password'] != ''`(L83) check only happens when `$changedEmail == 1`(L81)
https://github.com/Leantime/leantime/blob/23e0799206a5bcd2ff033203816abe3f661cd2bd/src/domain/users/controllers/class.editUser.php#L78-L88
so this is hashing an empty string if `$_POST['password']` is empty.
https://github.com/Leantime/leantime/blob/23e0799206a5bcd2ff033203816abe3f661cd2bd/src/domain/users/controllers/class.editUser.php#L58-L69
This is why #412, #416, #427 happens.
The original nested `if`s between L78 to L114 is a little bit confusing, so instead of fixing the `if`s, I decide to read the original hashed password from `$row`, and change the value if passwords are match and not empty.

fix: prevent password change if password is empty

---

src/domain/tickets/js/ticketsController.js

Replaced parseInt with parseFloat to allow summation of plannedHours, remainingHours and loggedHours as float instead of integer, therefore keeping the info after the decimal separator

Summation as floats

---

src/domain/dashboard/templates/show.tpl.php
src/domain/tickets/templates/showKanban.tpl.php

Small usability improvement: When adding a new To-Do on the kanban board,
the headline field will be focused once the jQuery transition has finished.

Focus headline when creating new todo

---

src/core/class.mailer.php

UTF-8 charset was set only in SMTP mode :
```
if($config->useSMTP === true) {
...
$this->mailAgent->CharSet = 'UTF-8';
}
```
I've moved it above the "if" statement so that it applies to both SMTP and php Mail(). Character encoding for accentuated characters is now correct even with the php Mail() builtin function (it was not the case before).

set UTF-8 for both SMTP and php Mail

---

resources/language/de-DE.ini
resources/language/de-DE_informal.ini
resources/language/en-US.ini
src/domain/clients/controllers/class.showClient.php
src/domain/clients/templates/showAll.tpl.php
src/domain/clients/templates/showClient.tpl.php
src/domain/tickets/templates/showKanban.tpl.php
src/domain/tickets/templates/submodules/ticketDetails.sub.php

Closes #702 
Displays the client & ticket ID in certain places:
| Page | What |
| --- | --- |
| Kanban | Ticket ID |
| Ticket Details | Ticket ID |
| All Clients Table | Client ID |
| Client Details | Client ID |
---

Display certain IDs in frontend

---

createReleasePackage.sh

Issues is the "leantime/." path in the zip command. Just leantime like in the tar is good.
Also 
- Removed the createReleasePackage.sh file that is in the repository now
- Added the -p paramter to mkdir release (only if directory does not already exists)
- Remove leftover leantime directory before pulling the latest from Github (should never happen, but we both know Murphy).
- Added documentation
Open questions
==========
Is the .idea directory needed for release?

Zip not readable in Windows

---

createReleasePackage.sh

This pulls the version out of the appSettings.php file, so you don't have to add it as a parameter.
You can still add a parameter; this will be added after the version 
(createReleasePackage "-alpha" would result in "Leantime-v2.2.4-alpha.zip" (and tar.gz)
This needs to be tested on a mac before being accepted.

Easy version in createReleasePackage.sh

---

createReleasePackage.sh

Removing the uncompressed JS folders and files (in src/domain and in public/js)
1. find all directories with name 'js' and remove this directory.
2. find and remove all files within public/js (that is not public/js itself) and where the name does not contain the string 'compiled'.
**note**
- the public/js one creates 2 errors where he wants to remove files that are already removed. 
- This can be ignored - although not as pretty as I would like.

Removing the uncompressed JS

---

createReleasePackage.sh

By removing the font used for labels under the qr-code (what we don't use at the moment), we can reduce the Release by ~15MB.

Remove font of qr-code plugin

---

config/configuration.sample.php
public/backup.php
src/core/class.db.php
src/core/class.install.php

Description:
I recently had issue with database configuration that is not using default 3306 port. So, I tried adding the port support in these files.
**configuration.sample.php**
- new port variable.
- new environment variable for port.
**class.db.php**
- new port variable
- add port to existing pdo connection string
**class.install.php**
- new port variable
- add port to existing pdo connection string
**backup.php**
- add port flag to mysqldump command
pl. sorry if I made any mistake, this is my first github PR, all advice are welcome.

Add support for port in pdo mysql

---

README.md

Updated the badges so
- license leads to the license information
- Version leads to the release page
- Docker hub leads to the docker hub
- Discord already lead to discord, but now with correct Github syntax

Updated "badges" with links

---

src/domain/tickets/js/ticketsController.js
src/domain/timesheets/js/timesheetsController.js

**According to issue #875** with broken export with utf-8 characters in datatables export button by adding charset: 'utf-8' and bom: true in datatables button
**Before fix**
**After fix**

fix: issue#875 add support for utf-8 character in datatables export button

---

src/domain/projects/templates/showProject.tpl.php

Replaced Slack logo due to ERR 304 with a smaller, higher quality SVG version from a cdn.

Replaced Slack logo due to ERR 304

---

src/core/class.db.php

If a database connection fails, I extended the standard error.
Added a check for php-PDO
Added a check for php-pdo_mysql
Added a dump of the error if debug is on.

Added checks and dump the error if debug is on

---

config/configuration.sample.php

This creates a timestamp (last change date of the config file) in the session variable 
When the timestamp does not match the current value in the session, the session is invalidated (and reloaded)

update the sample config

---

src/core/class.autoload.php
src/core/class.template.php
src/domain/calendar/templates/addEvent.tpl.php
src/domain/calendar/templates/delEvent.tpl.php
src/domain/calendar/templates/editEvent.tpl.php
src/domain/calendar/templates/showAllGCals.tpl.php
src/domain/calendar/templates/showMyCalendar.tpl.php
src/domain/clients/templates/delClient.tpl.php
src/domain/clients/templates/editClient.tpl.php
src/domain/comments/repositories/class.comments.php
src/domain/projects/templates/delProject.tpl.php
src/domain/tickets/templates/delTicket.tpl.php
src/domain/tickets/templates/newTicket.tpl.php
src/domain/tickets/templates/showAll.tpl.php
src/domain/tickets/templates/showKanban.tpl.php
src/domain/tickets/templates/showTicket.tpl.php
src/domain/users/templates/delUser.tpl.php
src/domain/users/templates/editUser.tpl.php
src/domain/users/templates/newUser.tpl.php
src/domain/users/templates/showAll.tpl.php

If a class from a vendor package matches the naming convention of `leantime`, loading the class fails because the system assumes that it is a `leantime` class.
=> Update code to only load a `leantime` class if the file exists.
There exist a type bug in the comments repository
=> correct it.
Chevron buttons is create/edit user did not show.
=> Added missing 'pa' class.

Proposed corrections for various bugs

---

src/domain/general/templates/headMenu.tpl.php
src/domain/general/templates/loginInfo.tpl.php

Add a caret-down next to the new company management / administration menu on the top right to show that it is a drop-down menu, rather than a function, consistent with the profile menu next to it.
Remove the name from the profile menu item (only show the image) to make it consistent with the overall menu items that only show icons, rather than text.
An alternative would be to have a text for all items (at it was the case in some old version). I prefer the new set-up.

Make top right menus UI consistent

---

src/core/class.theme.php

Correct bugs in core/class.theme resulting from referencing non-existing variables corrected.

Correct bugs in core/class.theme

---

src/layouts/app.php

Remove "http:" prefix for logo image path to avoid SSL warning for non-secure image loaded

SSL warning fix

---

app/core/class.defaultConfiguration.php
app/core/class.environment.php
app/domain/auth/services/class.auth.php
app/domain/ldap/services/class.ldap.php
config/configuration.sample.php

Removes LDAP parameters from configuration that are unused and could mislead users.
Signed-off-by: Silvio Gissi <silvio@gissilabs.com>

LDAP: Cleanup unused parameters

---

config/appSettings.php

this is because its being used in places in the system(index.php), and post upgrade caused an error. We should clean up its usage first. I also think we need to push out a new version

Restore getRequestURI to appsettings

---

app/domain/oidc/services/class.oidc.php

Hi,
someone contacted me because their OIDC-Connection wasn‘t working.
The header key is case sensitive, but shouldn‘t be. So I just turn copy them all to lower space and then check their value.

prevent OIDC header capitalization errors

---

app/domain/oidc/services/class.oidc.php

this is because this is the generally expected format, but sometimes its sent with additons like application/json+xyz or no type at all(in the case of azure)

update OIDC to use json decoding by default

---

app/command/class.addUserCommand.php
app/command/class.migrateCommand.php
app/domain/api/services/class.api.php
app/domain/auth/controllers/class.userInvite.php
app/domain/install/controllers/class.index.php
app/domain/users/controllers/class.editOwn.php
app/domain/users/repositories/class.users.php
app/domain/users/services/class.users.php

Hi,
I found a case (editing a user via RPC call) where the password was not hashed properly.
I thought that it might be a good idea to simply have the hashing happen in the user repository, so that one doesn't have to remember about it.
I shouldn't have broken anything, but I haven't been able to test the code, so I highly advise  a review.
Thanks for the amazing software.

Password hash at User Repository level

---

app/domain/users/controllers/class.editUser.php
app/domain/users/repositories/class.users.php

Hi,
I was facing issue when editing a user from an Owner account. This was leading to a password change (due to a double hashing of password) and the modified user was not anymore able to connect. This is probably a side effect of the PR #1636 
I made some checks to not update the password if not provided to editUser function and removed the value from the editform.
I was not able to do extended check, so it this change has to be taken with care

Conditional change password by edituser 

---

app/domain/projects/services/class.projects.php

Correct usage of the 'notifyProjectUsers' method with the line 'return $user != $notification->authorId;', see: https://github.com/Leantime/leantime/blob/98f0bb4af4763c44a007942e6b8d6c40b79b3a1f/app/domain/projects/services/class.projects.php#L171

#1505 #1528 Fix: Email notifications about changes are sent to the change owner.

---

app/Domain/Tickets/Templates/showKanban.tpl.php
public/assets/css/components/kanban.css

On the Kanban show page, there is an issue with long timeline names causing the text to overflow from the card. This problem persists across all browsers
This is causing issues with Kanban Styles. I included some new styles for milestone into the kanban section, also, added a new title tag to allow the user see the full text information
-  Go to any project
- Create a new milestone with long text
- Set this milestone to any task
- See the kanban view page
~~- [ ] My change requires a change to the documentation.~~
~~- [ ] I have updated the documentation accordingly.~~

Bug - Fix kanban milestone tag overflow out of the card

---

app/Domain/Menu/Templates/Submodules/projectSelector.sub.php

For the sidebar, when you click the name project options, the list of “projects” show the icon as it was opened and you have to click twice to see the list for each client.
This issue is causing bad UI/UX experience
[Leantime.webm](https://github.com/Leantime/leantime/assets/645526/493d709d-194e-4e24-8b8b-547ceed201b3)
[Leantime (1).webm](https://github.com/Leantime/leantime/assets/645526/fc029dcd-f09d-48b1-9a18-bbee520774b2)
~~- [ ] My change requires a change to the documentation.~~
~~- [ ] I have updated the documentation accordingly.~~

Fix toogle issue for current project menu

---

CONTRIBUTING.md

Fixes the following issues:
- GitHub Flow documentation has moved (the old link is redirecting to the GitHub Docs homepage) [Old Link](https://guides.github.com/introduction/flow/index.html) | [New Link](https://docs.github.com/en/get-started/quickstart/github-flow)
- The link to the Draft.js contributing guidelines was pointing to a specific ref that appears to not exist anymore (I replaced it with the most recent ref, which was committed much earlier than Leantime's CONTRIBUTING.md was created, so I assume that's the most relevant version) [Old Link](https://github.com/facebook/draft-js/blob/a9316a723f9e918afde44dea68b5f9f39b7d9b00/CONTRIBUTING.md) | [New Link](https://github.com/facebookarchive/draft-js/blob/5dd99d327066f5f0b30b95ab95770822cff1ac65/CONTRIBUTING.md)
Also fixes a typo …

Fix Broken Links in CONTRIBUTING.md

---

README.md

**What set up are you using**
**Describe the bug**
The instructions for the [Docker development installation](https://github.com/Leantime/leantime?tab=readme-ov-file#development-installation-via-docker) currently point to Leantime living on port `8080`, but this is incorrect and should be port `8090` instead. 
The port changed between these two in the [docker-compose.yaml](https://github.com/Leantime/leantime/blob/master/.dev/docker-compose.yaml) file and this may not have been updated in the readme.
**To Reproduce**
Steps to reproduce the behavior:
1. Install the development environment via Docker
2. Navigate to `localhost:8080` and `localhost:8090`
**Expected behavior**
Expect Leantime on `localhost:8080` per readme, but it is on `localhost:8090`.
**Leantime Version**
v2.4.1
**Server** …

Update port for Docker development environment in README

---

app/Domain/Canvas/Services/Canvas.php

fix: canvas repository not found on blueprints

Fix: canvas repository not found on blueprints

---

README.md

This adds a step-by-step GUI-based guide on enabling the PATCH method in IIS, which is often not enabled by default (afaik.)
Without the PATCH method being accepted by the server some small functionalities within LeanTime don't work quite right, primarily the tutorial popups keep appearing on every page after each authentication/log on even if the user clicks the "close and don't show again" link, as this preference is set via a PATCH.
Unfortunately this is an IIS thing and I can't find a way to enable this in the codebase only (via web.config for example) without also touching the IIS config somehow. This method as written seems like to simplest to distribute to IIS users.

Adds IIS-specific installation note to README.md

---

app/Domain/Notifications/Services/Messengers.php

The current Slack and Mattermost notifications were not sending much information. For example, when moving a card, it just said "Task was updated", but nothing else was shown. So I tried Trello's integrations and updated the Leantime with more information. Previous notifications were like this (Spanish):
To this:
So, now:
- The summary just shows what happened, without the ticket ID
- The clickable area is just the task name
- The project is shown in bold
- The status of the card is shown below
More information may be added easily, but I don't think a client, for example, needs to know the priority or other internal labels.
Here you can also see a comment:
And the same goes for Mattermost:

Improved Slack and Mattermost notifications

---

.dev/.env

Fixed some Typos

---

app/Domain/Projects/Templates/newProject.tpl.php
app/Domain/Projects/Templates/showProject.tpl.php
app/Domain/Projects/Templates/submodules/projectDetails.sub.php
app/Domain/Tickets/Templates/submodules/ticketDetails.sub.php

**Description**
This PR provide fix of textbox size in leantime v3 for the new leantime UI that comes with rounder textbox border. This result in some of the textbox contents were cropped out. Please refer to screen capture below
- Project to-do status sort order textbox (existing status and add new status)
Before
After
- Date textbox (new project, project detail, ticker detail)
Before
After

Fix cropped textbox content effected by rounder textbox border.

---

app/Domain/TwoFA/Templates/verify.tpl.php

Hi
Very minor fix to sets focus on the 2FA verify field and thereby removes the need for that extra click one forgets before entering the numbers form ones 2FA app.

Fix: Added autofocus to 2fa verify HTML field

---

app/Domain/Timesheets/Repositories/Timesheets.php
app/Domain/Timesheets/Templates/showAll.tpl.php

Added milestone and tags column to all timesheet view (which also exports them in the CVS export, which then can be used to make pivot-tables using these fields).

Added milestone and tags to all timesheet view

---

app/Domain/Plugins/Templates/partials/installed/plugincontrols.blade.php

Minor markup fix in plugin settings:
**Before**:
**After**:

Plugin settings minor markup fix

---

app/helpers.php

Hello !
There is currently an issue with the file download script which returns the "No Access" image for file downloads when the users are logged in through an OIDC provider.
This seems to be related to the fact that the download script does not load the full application, and some settings are missing.
This patch loads the app settings in the bootstrap_minimal_app function.
This has been tested and is working on a production instance with OIDC login.
I don't know if this is the best way to implement this. Tell me if there are changes to do.
Thanks !
Best regards

Download files issue when using OIDC login provider

---

app/Core/ConsoleKernel.php

https://github.com/Leantime/leantime/issues/2356
Fixes typo in parameter name.

2356: Fixed typo in parameter name

---

app/Domain/Projects/Templates/duplicateProject.tpl.php

https://github.com/Leantime/leantime/issues/2358
Fixes call to undefined method.

2358: Fixed call to undefined method

---

app/Domain/Files/Controllers/Get.php

Problem described on Discord, see: https://discord.com/channels/990001288026677318/1212409774092718090/1212409774092718090)
Adding a docx files to a todo works fine, but trying to download it results in 500 with the following information:
```
ErrorException:
Warning: Undefined array key "docx"
at /var/www/html/app/Domain/Files/Controllers/Get.php:105
at Leantime\Domain\Files\Controllers\Get->getFileLocally('eb3d6a81e7906c4c96c151b0929a26bd', 'docx', 'ticket', 'badania swialo niebieskie_2 (1)')
(/var/www/html/app/Domain/Files/Controllers/Get.php:55)
at Leantime\Domain\Files\Controllers\Get->get(array('module' => 'ticket', 'encName' => 'eb3d6a81e7906c4c96c151b0929a26bd', 'ext' => 'docx', 'realName' => 'badania swialo niebieskie_2 (1)', 'act' => 'files.get')) …
```

A fix for mime types handling

---

app/Command/AbstractPluginCommand.php
app/Command/DisablePluginCommand.php
app/Command/EnablePluginCommand.php
app/Command/InstallPluginCommand.php
app/Command/ListPluginCommand.php
app/Command/RemovePluginCommand.php

https://github.com/Leantime/leantime/issues/2363
Adds commands to manage plugins:
```sh
$ bin/leantime
…
plugin
plugin:disable        Disable a plugin
plugin:enable         Enable a plugin
plugin:install        Install a plugin
plugin:list           List all plugins
plugin:remove         Remove a plugin
```

Added plugin commands

---

app/Domain/Tickets/Repositories/Tickets.php

https://github.com/Leantime/leantime/issues/2373
Avoids using 'GROUP BY' to speed up ticket fetching. 
Before: https://app.screencast.com/qXbrfFa9O5vC5
After: https://app.screencast.com/u58mwMQoBOIly
If your code does not pass the requirements on the checklist, you should add a comment explaining why this change
N/A

#2373: Updated ticket fetching SQL

---

app/Domain/Tickets/Controllers/ShowTicket.php
app/Domain/Tickets/Templates/submodules/timesheet.sub.php
app/Domain/Timesheets/Controllers/AddTime.php
app/Domain/Timesheets/Controllers/EditTime.php
app/Domain/Timesheets/Controllers/ShowAll.php
app/Domain/Timesheets/Controllers/ShowMy.php
app/Domain/Timesheets/Controllers/ShowMyList.php
app/Domain/Timesheets/Js/timesheetsController.js
app/Domain/Timesheets/Repositories/Timesheets.php
app/Domain/Timesheets/Services/Timesheets.php
app/Domain/Timesheets/Templates/editTime.tpl.php
app/Domain/Timesheets/Templates/partials/stopwatch.blade.php
app/Domain/Timesheets/Templates/showAll.tpl.php
app/Domain/Timesheets/Templates/showMy.tpl.php
app/Domain/Timesheets/Templates/showMyList.tpl.php
app/helpers.php
composer.json
composer.lock

https://github.com/Leantime/leantime/issues/2322
Look into timezone handling and the conversion of dates. 
* Switched to using carbon (https://carbon.nesbot.com)  for date handling in timesheets
* Ensure date are in UTC in all PHP code and first converted on display in UI to local timezone and format.
* Added helper to `format()` to help during transition to carbon (as this is only change in timesheets for now)
* Ensure newly create and user provided dates are converted to UTC (and not created as UTC)
N/A
Tests can be found in https://github.com/Leantime/leantime/pull/2377

Timesheet fixes - retry - part II

---

.idea/leantime-oss.iml
app/Domain/Dashboard/Controllers/Show.php
app/Domain/Menu/Services/Menu.php
app/Domain/Projects/Services/Projects.php

https://github.com/Leantime/leantime/issues/2392
Adds a `getCurrentProjectId` function in `Leantime\Domain\Projects\Services\Projects` and uses it instead of `$_SESSION['currentProject']` in select places (the ones calling [Projects::getProject()](https://github.com/Leantime/leantime/blob/6635c4d3bb5b65adff5ea877eb6273b13784b0a9/app/Domain/Projects/Services/Projects.php#L101)).

Issue 2392

---

app/Domain/Plugins/Templates/partials/installed/plugincontrols.blade.php

https://github.com/Leantime/leantime/issues/2389
Shows "Settings" link only on *enabled* plugins.
Before: 
After:

Added check for plugin enabled on settings link

---

app/Domain/Api/Controllers/Users.php
public/assets/js/app/core/editors.js
public/assets/js/libs/tinymce-plugins/mention/plugin.js

https://github.com/Leantime/leantime/issues/2380
Fixes user mentions by
1. Patching [tinymce-mention](https://github.com/StevenDevooght/tinyMCE-mention) (see below for details)
2. Adding and using a simple `query` filter on `/api/users?projectUsersAccess=current`
Details on how to fix the "query" issue in tinymce-mention:
* https://github.com/StevenDevooght/tinyMCE-mention/issues/93#issuecomment-1853296121
* https://github.com/StevenDevooght/tinyMCE-mention/issues/1#issuecomment-22869442
Before:
After:

Fixed user mentions

---

app/Language/en-US.ini

#2403 
Dropping in the en-US translation of `text.full_lean_canvas_helper_content` in app/Language/de-DE_informal.ini into app/Language/en-US.ini
Ideally, the fullLeanCanvas modal will display that description instead of the token `text.full_lean_canvas_helper_content` when en-US is the default language.

2403 Added en-US translation

---

app/Domain/Projects/Services/Projects.php

This PR closes this issue https://github.com/Leantime/leantime/issues/2366
The dashbaord page is crashing with 500 error because the init value of $_SESSION['currentProject'] is an empty string. Setting the init value to 0 solved the problem. The check in the getProject method didn't prevent the issue because it is checking on null

Set init value of $_SESSION['currentProject'] to 0 instead of ''

---

app/Domain/Ldap/Services/Ldap.php

https://github.com/Leantime/leantime/issues/2289
https://github.com/Leantime/leantime/issues/2080
Multiple LDAP entries were showing up as blank due to the way php ldap normalizes camelCase to lowercase. Since some ldap entries are all lowercase by default, they appeared normally while others did not.

Resolve LDAP naming conventions 2289 & 2080

---

app/Domain/Files/Controllers/Get.php

For downloads with unknown file types (like xls, zip), the content is displayed inline in Chrome. Works fine in Firefox without this change.
No ticket. Reported on Cloudron forum at https://forum.cloudron.io/topic/11347/issue-with-file-opening-downloading-in-leantime-application
content-disposition is not set correctly for chrome browser when downloading unknown file types
No change in UI
I have only tested this change locally on Cloudron and have not run the tests.

Fix content-disposition header

---

app/Language/zh-CN.ini

Wrong % symbol is used, causing failure of text rendering.
Translation only. 

fix incorrect symbol in the translation for zh-CN

---

.idea/leantime-oss.iml
.idea/php.xml
.idea/vcs.xml
CHANGELOG.md
app/Domain/Tickets/Templates/milestoneDialog.tpl.php

#2482 
Milestones edit screen now selects correct project and doesn't show plan/strategy milestones
- [x ] My code passes all test cases.
- [ x] My code passes our static analysis suite.
- [ x] My code passes our continuous integration process.

Milestone project selector fix

---

CHANGELOG.md
app/Domain/Projects/Repositories/Projects.php
app/Domain/Projects/Services/Projects.php

#2474 Addproject method not returning project id
addProject() now returns project id on successful creation, otherwise false

Add project return

---

app/Core/Middleware/RequestRateLimiter.php

N/A
Along with the newly added x-ratelimit headers, "Retry-After" needs to be added as it is a standard and sometimes expected.
N/A

Add Retry-After header to support standard ratelimit response expectations

---

app/Domain/Tickets/Repositories/Tickets.php

None
In most of other get ticket methods, zp_tickets.userId is included, but not in this simpleTicketQuery. It doesn't make sense.

Update Tickets.php to include zp_tickets.userId in simpleTicketQuery

---

app/Domain/Comments/Services/Comments.php

None
Before change, the comment notification includes a url to the task such as `https://leantime.io/tickets/showTicket/325&projectId=10`
It is not working because it lacks `#/`
It should be `https://leantime.io/#/tickets/showTicket/325&projectId=10`
Without this change, the link doesn't lead the user to the task but leads to something like `https://leantime.io/tickets/showKanban?showTicketModal=325`. In this case, the task window does not pop up.

Update Comments.php to fix ticket comment notification url

---

app/Domain/Sprints/Templates/sprintdialog.tpl.php

No ticket spotted... i rand into the bug and just fixed it.
When using the button "create sprint" the produced html is buggy and lead to wrong project assignation if the default choice is not made.
There is no visible difference except the list does not show projects twice any more and the projects id are correctly associated with project names.
N/A
The change made consists in removing the duplicate foreach loop on select. It was probably just a copy paste made twice.

Fixing template for new sprint creation

---

README.md

Changed the requirements from MySQL 5.7+ to MySQL 8.0+ 
MySQL 5.7 is not supported anymore by Oracle since 2023-10-31 and will not get any security updates. 
We should not encourage our users to use old and insecure software.
MySQL 8.0 is the lowest version that is still supported by Oracle and is a LTS release 
(Generic support until 2025-04-30 and extended until 2026-04-30)

Update README.md for newer mysql version

---

app/Core/Middleware/Updated.php

If a db was updated but had to be downgraded later on the update check in the middleware prevented the app from registering valid version. This is now fixed
[x] Fix
[] Feature
[] Cleanup

Improved update check

---

app/Domain/Ldap/Services/Ldap.php

The  Problem:
Even if you set a domain for the LEAN_LDAP_LDAP_DOMAIN environment variable, you will not be able to login using only the user ID, you can only login using the full form, user@domain.
**Example login entry:**
*Before changes:*
* "user@domain", result Login
* "user", result ```Error 500```
*After changes:*
* "user@domain", result OK
* "user", result OK
**Type**
[X] Fix
[] Feature
[] Cleanup

Fix LDAP AD login without domain (using only user ID).

---

app/Domain/Queue/Repositories/Queue.php

New users are set to invited while the email queue will only look for active users. This causes a 500 
#2698
[x] Fix
[] Feature
[] Cleanup

New user email queue bug

---

app/Domain/Projects/Templates/showProject.blade.php
public/mix-manifest.json

Slack logo in the Integrations page is not loaded because of CSP Policy, this PR will solve that issue.
Before changes
After changes

fix: add slack logo prevent CSP policy error

---

app/Domain/Oidc/Controllers/Callback.php
app/Domain/Oidc/Services/Oidc.php

This PR solves several bug fixes when using OIDC with Leantime. Notably, i've resolved issues related to:
- Ensuring get userinfo oauth2 endpoint is called when the decodeJWT function fails
- Returning to the `/auth/login` URL in case the callback service fails, thereby preventing infinite redirect loops.
These changes will resolve the issue of infinite redirect loops experienced by users who integrate Leantime with Keycloak.

Fix OIDC bugs

---

app/Domain/Auth/Templates/login.blade.php

hide `label.or` when oidc is enabled with noLoginForm is true
before:
after:
- [x ] Fix

Fix label OR in form login template

---

app/Core/Console/ConsoleKernel.php

The commands are cached in cache store and not in session object.
Fixes #2710
Long ago this was in _SESSION. Then, it moved to session() and now it's in the Cache
https://github.com/Leantime/leantime/issues/2710
- [ X ] Fix
No change in UI

cli: fix crash when running commands

---

app/Core/Db/DbColumn.php
app/Domain/Connector/Models/Integration.php
app/Domain/CsvImport/Templates/upload.tpl.php
app/Domain/Projects/Services/Projects.php

Fixing CSV upload and import issues

Csv importer

---

app/Domain/Projects/Js/projectsController.js
app/Domain/Projects/Templates/newProject.blade.php
app/Domain/Projects/Templates/showAll.blade.php

ui issues fixed; newProject form input replaced and fixed script

All project fixes

---

app/Domain/Timesheets/Templates/showAll.blade.php

client access issue in all-timesheets fixed

client issue fixed in all timesheets

---

public/assets/css/components/structure.css
public/theme/default/css/dark.css

Pseudo element on overlay used to darken the background takes over dropdown events in header. 
Thank you to Discord User _strangecameleon_ for debugging this with me! 

fix: pseudo element on overlay took over click events on dark mode

---

helm/templates/deployment.yaml
helm/templates/pvc.yaml
helm/templates/service.yaml
helm/values.yaml

Changed service target port and container port to 8080 to match leantime image config.
Made the storageClass optionnal, Empty will use system default Added a configuration for the LEAN_SESSION_SECURE with true as default

Fixed helm chart services and deployment

---

app/Core/Providers/Session.php

Fixes issue where sessions folder doesn't exist after system update. Ensures sessions folder is created before adding sessions
#2993 2993
- [x ] Fix

fix: Ensure sessions folder exists before putting files into it

---

app/Domain/Wiki/Repositories/Wiki.php
app/Domain/Wiki/Templates/articleDialog.tpl.php

This is a rapid fix from the discussion 
https://github.com/Leantime/leantime/discussions/2370
While it doesn't fully addresses the request (manually ordering of wiki headers) it orders alpabetically both the wiki tree (without changes to the original code) and the voices inside the "parent" combobox.
I saw that you already have a "sortindex" field in the table, so probably you are already working on it, but in hte meanwhile it can put a bit of order in managing wikis.
The combobox avoids that a circular reference can be created by hiding the current wiki page and all its children.
I nearly don't know PHP (I programmed it for a while when version 4 came out) so the code is probably less than ideal.
Hope this helps.
[*Please add a link to the GitHub issue being addressed by this change.* …

Order Wiki headers

---

app/Domain/Api/Controllers/Jsonrpc.php

Includes `int` (number) in the allowed id types in the JSON RPC response (cf. https://www.jsonrpc.org/specification#response_object)
https://github.com/Leantime/leantime/issues/3063

Update type declaration for id parameter in JSON RPC response

---

tests/Acceptance/API/ApiCest.php

Fixes acceptance tests that broke in https://github.com/Leantime/leantime/pull/3064.
> [!NOTE]
> [The “pint” check](https://github.com/Leantime/leantime/actions/runs/16164821085/job/45624135644?pr=3066) now fails so further cleanup is needed (in another pull request). 
Follow-up on https://github.com/Leantime/leantime/issues/3063

Fix JSON RPC acceptance tests

---

README.md

- there is already a formatted list [directly above this paragraph](https://github.com/Leantime/leantime/tree/03d36dd8ff2df63c25172afc7252d76bb5c8f1be?tab=readme-ov-file#system-requirements)
- https://github.com/Leantime/leantime/commit/5f01410766218631ccb47e3697bc58dbdbe3dd0b seemed to have accidentally partially duplicated the list
n/a
Screenshot of README with the duplicated list/paragraph removed:
You might be interested in adding [a `<details>` spoiler tag](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287) to put the list behind a dropdown; I can make that change if desired, but left this PR as a clean fix

docs: remove duplicated PHP Extensions list
