README.md, config/configuration.sample.php, config/settings.php, package-lock.json, src/content.php, src/domain/ideas/js/ideasController.js, src/domain/ideas/templates/ideaDialog.tpl.php, src/domain/leancanvas/js/leancanvasController.js, src/domain/leancanvas/templates/canvasDialog.tpl.php, src/domain/retrospectives/templates/retroDialog.tpl.php
- Fixed icon issues
- Allow Save and Close on ideas, retrospectives and canvas boards
=> Misc Patches

src/core/class.db.php, src/core/class.install.php, src/domain/retrospectives/templates/retroDialog.tpl.php, src/install.php
- Ensure strict mode is off (mysql 5.7)
- Show mysql error messages on install screen
=> Install patches

nginx.conf
This PR includes nginx configuration with SSL enabled, with additional optimisations.
Should do what is asked in #62
=> Add nginx configuration with SSL enabled

config/settings.php, package.json, public/js/libs/simpleGantt/frappe-gantt.min.js, src/content.php, src/core/class.application.php, src/core/class.fileupload.php, src/core/class.frontcontroller.php, src/domain/dashboard/js/dashboardController.js, src/domain/dashboard/templates/show.tpl.php, src/domain/general/controllers/class.footer.php, src/domain/general/controllers/class.menu.php, src/domain/general/templates/footer.tpl.php, src/domain/general/templates/menu.tpl.php, src/domain/help/templates/kanban.tpl.php, src/domain/help/templates/notfound.tpl.php, src/domain/help/templates/retrospectives.tpl.php, src/domain/projects/controllers/class.newProject.php, src/domain/projects/controllers/class.showAll.php, src/domain/projects/repositories/class.projects.php, src/domain/projects/services/class.projects.php, src/domain/projects/templates/newProject.tpl.php, src/domain/retrospectives/templates/showBoards.tpl.php, src/domain/tickets/repositories/class.tickets.php, src/domain/tickets/templates/roadmap.tpl.php, src/domain/tickets/templates/showKanban.tpl.php, src/domain/users/controllers/class.editUser.php, src/domain/users/templates/editUser.tpl.php, src/domain/users/templates/newUser.tpl.php
- Fixed scroll position for Gantt charts
- Removed Y scroll on Gantt chart
- Fixed 0 project user experience #61
- Fixed wrong exception object instantiation in file handler
- Removed old permission validation in frontcontroller (was not used)
- Fixed/removed javascript due date update call when editing a To-Do
- Added version to footer
- Renamed "Progress Review" to "Retrospectives"
- Fixed close lightbox call in helper content modals (kanban and retros)
- Project creator is now assigned to a new project by default (can be unchecked)
- All projects view (for admins) only showed user projects.
- Removed footer placeholder from content template
=> Misc bug fixes and enhancements

config/settings.php, nginx.conf, public/.htaccess, src/core/class.application.php, src/core/class.db.php, src/core/class.install.php, src/core/class.login.php, src/core/class.mailer.php, src/domain/setting/repositories/class.setting.php, src/install.php, src/update.php
- Update tables to utf8mb4
- New update routine and fixes in installation
- Mailer fix to use utf8 in emails
=> Hotfixes 2.0.4

public/css/style.default.css
On scrolling only .rightpanel div moves.
=> Leftpanel and header fixed position

src/domain/ideas/templates/ideaDialog.tpl.php, src/domain/projects/controllers/class.delProject.php, src/domain/projects/templates/delProject.tpl.php, src/domain/tickets/templates/delTicket.tpl.php, src/domain/tickets/templates/roadmap.tpl.php
fix todo delete notice
fix project delete notice
reset project selection after deleting a project
fix milestone date issue
enhancement left and top bar fixed when scrolling
=> Version 2.0.9

public/index.php, src/core/class.application.php, src/domain/general/controllers/class.header.php, src/resetPassword.php
Quick fix: Making sure only one instance of login is passed into application layer.
Longer term fix: Make login singleton
=> fixed multiple reset email issue

config/settings.php, package.json, public/index.php, src/domain/clients/templates/showClient.tpl.php, src/domain/comments/templates/submodules/generalComment.sub.php, src/domain/dashboard/templates/show.tpl.php, src/domain/help/js/helperController.js, src/domain/projects/controllers/class.showProject.php, src/domain/projects/services/class.projects.php, src/domain/projects/templates/showProject.tpl.php, src/domain/sprints/controllers/class.editSprint.php, src/domain/tickets/controllers/class.delTicket.php, src/domain/tickets/templates/showAll.tpl.php, src/domain/tickets/templates/showKanban.tpl.php
- Fixes #143 permission issue when deleting todos
- Fixes #140 badly formatted URL
- Fixes #138 checks if a user is still assigned to a project at every call
- verified favicon is still there and working #136 
- Fixed multiple broken links after subfolder support was integrated
- Fixed badly formatted URL for helper content
=> Hotfixes 2.0.13

public/css/style.custom.php, public/css/style.default.css, src/core/class.mailer.php, src/domain/general/js/menuController.js, src/domain/general/templates/menu.tpl.php, src/domain/projects/controllers/class.newProject.php
- remove default tasks
- toggle large client list
=> Misc fixes

config/configuration.sample.php, config/settings.php, package.json, public/index.php, src/domain/comments/templates/submodules/generalComment.sub.php, src/domain/ideas/templates/advancedBoards.tpl.php, src/domain/ideas/templates/showBoards.tpl.php, src/domain/leancanvas/controllers/class.editCanvasItem.php, src/domain/leancanvas/templates/showCanvas.tpl.php, src/domain/leancanvas/templates/simpleCanvas.tpl.php, src/domain/projects/controllers/class.newProject.php, src/domain/retrospectives/templates/showBoards.tpl.php, src/domain/setting/templates/editBoxDialog.tpl.php, src/domain/tickets/templates/showKanban.tpl.php
- Fixed comment delete issues
- Fixed various broken links
- Fixed header warning when appURL was not set
=> Patches 2.0.14

README.md, config/configuration.sample.php, nginx.conf, package.json
This is an initial preview of one approach to environmental configuration.
=> environment in the config

config/settings.php, src/domain/tickets/templates/milestoneDialog.tpl.php, src/domain/tickets/templates/showAllMilestones.tpl.php
- version bump
- one more missed escape
=> Prep 2.1.1

src/domain/tickets/repositories/class.tickets.php, src/domain/tickets/templates/showAllMilestones.tpl.php, src/domain/timesheets/services/class.timesheets.php
=> Hour calculations

config/settings.php, resources/language/en-US.ini, src/core/class.install.php, src/domain/comments/templates/submodules/generalComment.sub.php, src/domain/projects/controllers/class.delProject.php, src/domain/projects/repositories/class.projects.php, src/domain/tickets/templates/showAll.tpl.php, src/domain/tickets/templates/submodules/subTasks.sub.php, src/domain/users/repositories/class.users.php
Fixing recent bugs. 
#257 #259 #258  #253 #266
=> Bugfixes 20102

config/settings.php, resources/language/en-GB.ini, resources/language/en-US.ini, resources/language/es-ES.ini, resources/language/nl-NL.ini, resources/language/ru-RU.ini, src/content.php, src/core/class.install.php, src/core/class.login.php, src/domain/calendar/repositories/class.calendar.php, src/domain/calendar/templates/showMyCalendar.tpl.php, src/domain/general/templates/header.tpl.php, src/domain/help/js/helperRepository.js, src/domain/leancanvas/templates/canvasDialog.tpl.php, src/domain/projects/services/class.projects.php, src/domain/projects/templates/showAll.tpl.php, src/domain/projects/templates/showProject.tpl.php, src/domain/projects/templates/submodules/projectDetails.sub.php, src/install.php, src/login.php, src/resetPassword.php, src/twoFA.php, src/update.php
Fixes #274 wrong validation value status in dropdown
Fixes #272 currentProject not changed from MyCalendar view
Fixes #271 add more users link broken on subfolder installations
Additional company name sanitation
=> Bugfixes 20103

config/settings.php, src/domain/projects/controllers/class.showProject.php, src/domain/timesheets/controllers/class.showMy.php
=> Bugfixes 20104

public/css/style.default.css
Made Menu Icon move within the logo
Currently the menu icon is under the "my portfolio" icon
def need a better solution
=> Temp Fix: Made Menu Icon move within the logo

src/domain/ideas/js/ideasController.js, src/domain/leancanvas/js/leancanvasController.js, src/domain/projects/js/projectsController.js, src/domain/tickets/js/ticketsController.js
Adds this feature to the editor...
=> NEW [FEATURE] Numbered list in the text fields #313

config/settings.php, resources/language/de-DE.ini, resources/language/en-US.ini, src/core/class.install.php, src/domain/comments/repositories/class.comments.php, src/domain/comments/services/class.comments.php, src/domain/comments/templates/submodules/generalCommentBottom.sub.php, src/domain/projects/controllers/class.showProject.php, src/domain/projects/repositories/class.projects.php, src/domain/projects/templates/showProject.tpl.php, src/domain/projects/templates/submodules/projectDetails.sub.php, src/domain/tickets/controllers/class.showTicket.php, src/domain/tickets/templates/showTicket.tpl.php
NEW - Possibility to change the order of the comments...
NEW - now the order sets also the position of the input textarea
NEW - Order of comments now available for comments in tickets
And adds pull request #347 - so you can use it as a patch
… Template additional Fields which will be directly usable in all project related situations
includes a db Update and for this we have to update the version to 2.1.5 - but this ist just for testing purpose - feel free to change...
=> NEW - Reorder comments

src/domain/comments/templates/submodules/generalComment.sub.php
With this patch you can use tinymce in the comments and subcomments
ref: https://github.com/Leantime/leantime/issues/341
=> Comment tiny mce

src/content.php, src/domain/users/controllers/class.editUser.php, src/domain/users/controllers/class.newUser.php, src/domain/users/repositories/class.users.php, src/domain/users/templates/editUser.tpl.php
FIX - BUG password mismatch did not work at all...
Reformats code with PHPStorm
Clears Feature Request #334
=> Edit Password of existing user - FIX for #334

.gitignore, config/configuration.sample.php, public/backup.php, public/download.php, resources/language/es-ES.ini, src/core/class.fileupload.php
* S3 Compatible Storage
* Backup Database with Cron
* Spanish Translation
=> S3 Compatible Storage, Backup Database with Cron, Spanish Translation

config/settings.php, package.json, src/domain/tickets/templates/showTicket.tpl.php
s Please enter the commit message for your changes. Lines starting
=> version bump

.gitignore, src/core/class.fileupload.php
The file class.fileupload.php have error with variable s3FolderName
=> Error Upload S3

src/domain/tickets/controllers/class.newTicket.php, src/domain/tickets/templates/newTicket.tpl.php
fixing URL issues in New To-Do page subfolder installation
=> fix url issues for new ticket

src/domain/leancanvas/templates/canvasDialog.tpl.php, src/domain/projects/templates/showProject.tpl.php, src/domain/retrospectives/templates/showBoards.tpl.php, src/domain/tickets/js/ticketsController.js, src/domain/tickets/templates/milestoneDialog.tpl.php
Add function `htmlEntities` into ticketsController.js
> htmlentities() is a function which converts special characters. This allows you to show to display the string without the browser reading it as HTML.
Using `$this` when call to object
Fix bug `Cross-site Scripting (XSS) - Stored in leantime/leantime`
Disclosure: https://huntr.dev/bounties/1cc6d108-3827-4b62-bcf2-24192af7057d/
=> Fix Multiple Stored XSS on featuers 'Milestones' , 'Research', 'Retrospective' and Stored XSS via filename when upload file

src/domain/help/templates/projectSuccess.tpl.php
Use message string defined in language files ('text.project_success') instead of hard-coded English message in projectSuccess.tpl.php
=> Use language variable instead of hard-coded english message

src/domain/projects/services/class.projects.php
Added the resetting of ticketlabels to the changeCurrentSessionProject function
=> Added resetting of ticketlabels

src/domain/comments/templates/submodules/generalComment.sub.php
Fix for issue 667: https://github.com/Leantime/leantime/issues/667
=> 667: displaying the correct name and dates on discussion replies

src/domain/dashboard/js/dashboardController.js, src/domain/reports/templates/show.tpl.php
=> fix misdisplayed of sprintBurndownChart

src/install.php
Closes #704 
This change will redirect users to the main page when trying to access `/install` and the installation process has already finished.
=> Prevent access to installation page after installation

public/css/vars.css.php, src/content.php
Company colors will take affect after this merge.
=> Accent Color Fix

gruntfile.js, package-lock.json, package.json, public/css/components/mobile.css, public/css/components/style.default.css, public/css/components/tables.css, public/js/app/core/custom.js, src/domain/clients/controllers/class.showAll.php, src/domain/general/js/menuController.js, src/domain/general/templates/loginInfo.tpl.php, src/domain/projects/controllers/class.showAll.php, src/layouts/app.php
#852 Patch calls on resize fixed
#766 Profile Icon now visible
#132 Better mobile version
=> Mobile Responsive Fixes

public/css/components/overwrites.css, src/core/class.template.php, src/domain/tickets/controllers/class.showTicket.php, src/domain/tickets/js/ticketsController.js, src/domain/tickets/templates/showTicketModal.tpl.php, src/domain/tickets/templates/submodules/ticketDetails.sub.php
#861 Save and close for todos is now working correct
=> Prettier notifications & Save And Close fix

src/core/class.language.php
Thank you @phulstaert for this great optimization
=> Caching parse ini results

public/cron.php, src/domain/users/controllers/class.editOwn.php
2 bugfixes for async mails feature
=> Asyncmails bf

src/domain/projects/repositories/class.projects.php, src/domain/sprints/repositories/class.sprints.php
&& in queries is depricated; using AND instead
Removed an end ?>
=> && in queries is depricated; using AND instead

config/configuration.sample.php
- reduce the amount of configEnvironmentHelper from 42 to 20 in a lot of cases (do not read S3 settings if useS3 is not true; same for ldap and mail)
- formatting closer to PSR-12
- useLdap set to boolean instead of undefined (=>string)
=> Optimize loops + formating + useldap as boolean

src/core/class.session.php
Fixes https://github.com/Leantime/leantime/issues/1001
=> Respect the session expiration for cookies

src/domain/dashboard/controllers/class.show.php
Fixing #1038: Project updates couldn't be deleted
=> Fix delete project update issue

src/core/class.mailer.php, src/domain/projects/controllers/class.showAll.php, src/domain/projects/repositories/class.projects.php, src/domain/projects/templates/showAll.tpl.php
=> Hide closed projects from project screen

src/domain/auth/controllers/class.login.php, src/domain/auth/templates/login.tpl.php, src/language/en-US.ini
=> Change input placeholder based on ldap availability

src/domain/comments/templates/submodules/generalComment.sub.php
=> Images were not visible in comments

src/domain/queue/services/class.queue.php, src/domain/setting/controllers/class.editCompanySettings.php, src/domain/setting/templates/editCompanySettings.tpl.php, src/domain/users/controllers/class.editOwn.php, src/domain/users/templates/editOwn.tpl.php, src/language/en-US.ini
=> Set email frequency defaults on company level

public/css/components/nav.css
=> Fix project selector overflow issue

src/core/class.application.php, src/domain/auth/controllers/class.login.php, src/domain/twoFA/controllers/class.verify.php
=> Fixing login redirects

public/css/components/style.default.css, src/core/class.mailer.php, src/domain/api/controllers/class.notifications.php, src/domain/api/controllers/class.users.php, src/domain/install/repositories/class.install.php, src/domain/menu/controllers/class.headMenu.php, src/domain/menu/templates/headMenu.tpl.php, src/domain/notifications/events/register.php, src/domain/notifications/repositories/class.notifications.php, src/domain/notifications/services/class.notifications.php, src/domain/projects/services/class.projects.php, src/language/en-US.ini
=> First draft of notifications

src/core/class.mailer.php, src/domain/timesheets/repositories/class.timesheets.php, src/domain/timesheets/templates/showMy.tpl.php
This also introduces a good method to make certain template outputs filterable in a flexible way.
I'll add this in a better way in the twig POC.
=> undoing a plugin specific change

src/domain/tickets/templates/submodules/timesheet.sub.php
=> Fixes #1185

src/domain/dashboard/templates/show.tpl.php, src/domain/menu/repositories/class.menu.php
=> Fix missing s in copy URL

config/appSettings.php, src/domain/canvas/controllers/class.pdf.php, src/domain/ideas/templates/advancedBoards.tpl.php, src/domain/minempathycanvas/controllers/class.pdf.php, src/domain/pageparts/templates/header.tpl.php, src/language/en-US.ini
=> 2.3.3 patches

public/css/components/nyroModal.css, src/core/class.application.php, src/core/class.controller.php, src/core/class.frontcontroller.php, src/core/class.template.php, src/core/model.CurrentUser.php, src/domain/api/controllers/class.notifications.php, src/domain/api/controllers/class.users.php, src/domain/canvas/templates/canvasDialog.inc.php, src/domain/minempathycanvas/repositories/class.minempathycanvas.php, src/domain/pageparts/controllers/class.header.php, src/domain/projects/repositories/class.projects.php, src/domain/projects/services/class.projects.php, src/domain/queue/repositories/class.queue.php, src/domain/tickets/controllers/class.showKanban.php, src/domain/tickets/controllers/class.showTicket.php, src/domain/users/controllers/class.editOwn.php, src/domain/users/repositories/class.users.php, src/domain/users/templates/editUser.tpl.php, src/language/en-US.ini
=> 2.3.4 patches

app/language/ar-SA.ini, app/language/de-DE.ini, app/language/en-GB.ini, app/language/en-PT.ini, app/language/es-ES.ini, app/language/et-EE.ini, app/language/fr-FR.ini, app/language/he-IL.ini, app/language/hu-HU.ini, app/language/it-IT.ini, app/language/ja-JP.ini, app/language/km-KH.ini, app/language/nl-NL.ini, app/language/no-NO.ini, app/language/pl-PL.ini, app/language/pt-BR.ini, app/language/pt-PT.ini, app/language/ru-RU.ini, app/language/sk-SK.ini, app/language/sl-SI.ini, app/language/sr-SP.ini, app/language/sv-SE.ini, app/language/tr-TR.ini, app/language/vi-VN.ini, app/language/zh-CN.ini, app/language/zh-TW.ini
Reverts Leantime/leantime#1336
=> Revert "New Crowdin updates"

app/domain/tickets/controllers/class.showTicket.php, app/domain/tickets/services/class.tickets.php
=> Ensure tasks stay within a project

app/domain/canvas/templates/element.inc.php, app/domain/ideas/controllers/class.advancedBoards.php, app/domain/ideas/controllers/class.showBoards.php, app/domain/ideas/js/ideasController.js, app/domain/ideas/repositories/class.ideas.php, app/domain/menu/js/menuController.js, app/domain/menu/repositories/class.menu.php, app/domain/tickets/js/ticketsController.js, app/domain/tickets/js/ticketsRepository.js, app/domain/tickets/models/class.tickets.php, app/domain/tickets/repositories/class.tickets.php, app/domain/tickets/templates/roadmap.tpl.php, app/domain/tickets/templates/showAll.tpl.php, app/domain/tickets/templates/showKanban.tpl.php, app/domain/tickets/templates/showList.tpl.php, app/domain/twoFA/templates/edit.tpl.php, public/css/components/kanban.css, public/css/components/mobile.css, public/css/components/tables.css, public/js/libs/simpleGantt/frappe-gantt.min.js, public/theme/default/css/theme.css
#1436 Remembers last idea view now
#1432 Show QR code secret for 2fa in case you don't have a camera
#1426 Close mobile menu on page reload
#1423 mobile canvas headers not visible
Moving items on the gant chart vertically is now possible
=> UI enhancements, idea link memory

app/domain/auth/controllers/class.login.php
https://github.com/m8than/googleSSO-leantime is the plugin.
=> Added a beforeAuth hook (to allow my google sso plugin to work)

app/core/class.application.php, app/domain/auth/controllers/class.login.php, app/domain/tickets/services/class.tickets.php
Fixed issue with jsonrpc api url check
=> Fixed issue with jsonrpc api url check

app/domain/oidc/services/class.oidc.php
Hi Leantime Team,
first of all I want to apologize.
Somehow a stray die(); snuck into my code. I'm not entirely sure how. I think I messed up the merge.
Anyway, this removes the die(); and another PHP-EOL which now let's users authenticate via Keycloak.
=> Fixed OIDC support

app/domain/calendar/controllers/class.showMyCalendar.php, app/domain/calendar/repositories/class.calendar.php, app/domain/calendar/templates/showMyCalendar.tpl.php, app/domain/tickets/repositories/class.tickets.php, app/domain/tickets/services/class.tickets.php
Adding done tasks and status to myCalendar view
=> Patches 2.3.21

app/domain/timesheets/templates/showMy.tpl.php
Destroying chosen and rebuilding it when there is a change (issue with the trigger)
=> Fixing issue with field project and todo in my timesheets view

app/domain/tickets/templates/showAll.tpl.php
I am sending a proposal to display a column with the task ID.
=> Add 'ID' column to the task list

app/domain/comments/services/class.comments.php
Fix "email_notifications.new_comment_todo_with_type_subject"
=> FIX broken translation key

app/language/en-US.ini
=> en-US.ini typo fix

app/core/class.events.php, app/domain/api/controllers/class.users.php, app/domain/menu/js/menuController.js, app/domain/pageparts/js/generalController.js, app/domain/pageparts/templates/header.tpl.php, app/domain/projects/controllers/class.newProject.php, app/domain/projects/controllers/class.showProject.php, app/domain/projects/repositories/class.projects.php, app/domain/projects/services/class.projects.php, app/domain/projects/templates/newProject.tpl.php, app/domain/projects/templates/submodules/projectDetails.sub.php, app/domain/tickets/js/ticketsController.js, app/domain/users/repositories/class.users.php, config/appSettings.php, config/configuration.sample.php, config/sample.env, logs/error.log, makefile, package.json, public/assets/js/app/app.js, public/assets/js/libs/jquery.nyroModal/js/jquery.nyroModal.custom.js, public/assets/js/libs/simpleGantt/frappe-gantt.min.js, public/assets/less/editor.less, webpack.mix.js
- Cache folder not writable bug
- tinymce css not correctly loading fonts
- removed console.logs
- removed var_dumps
=> Fixed multiple release issues

app/domain/auth/services/class.auth.php, app/domain/ldap/services/class.ldap.php, app/domain/users/repositories/class.users.php
Partial patch https://github.com/Leantime/leantime/issues/1761
Can you test it ?
Don't forget to adjust your .env file (phone value)!
```
LEAN_LDAP_KEYS="{
\"username\":\"sAMAccountName\",
\"groups\":\"memberof\",
\"email\":\"mail\",
\"firstname\":\"givenname\",
\"lastname\":\"sn\",
\"phone\":\"telephonenumber\",
\"jobTitle\":\"title\",
\"jobLevel\":\"employeeType\",
\"department\":\"department\"
}"
```
=> Patch Issue 1761

app/Domain/Tickets/Templates/showKanban.tpl.php, public/assets/css/components/kanban.css
Reverts Leantime/leantime#1875
PR set all dropdowns to 100% in kanban cards
=> Revert "Bug - Fix kanban milestone tag overflow out of the card"

app/Domain/Users/Repositories/Users.php
include missing file dependency for User repository
Issue reference: https://github.com/Leantime/leantime/issues/1900
=> Solve User dependencies with File::Class

app/Core/Environment.php
=> fix: resolved issue where env vars did not overwrite php config vars

app/Domain/Wiki/Repositories/Wiki.php
Bad variable name in function definition prevented Wiki Articles from being updated.
Fixes #1920
=> fix(Wiki): variable $article was $Article in function definition

app/Domain/Tickets/Js/ticketsController.js
=> fix(tickets): Javascript issue on save in list view

.dev/docker-compose.tests.yaml, app/Core/Environment.php, app/Domain/Oidc/Services/Oidc.php, app/Domain/Tickets/Js/ticketsController.js, tests/bootstrap.php
=> fix(tickets): Fixing non working ticket counter

config/configuration.sample.php, config/sample.env
Fixes some typos, improves formatting, and makes capitalization more consistent in `config/sample.env` and `config/configuration.sample.php`. Purely for readability purposes, no changed functionality.
=> Cleanup Sample Config File Comments

README.md
This Pull Request fixes a typographical error in the README.md file.
Corrected "offically" to "officially" in the README.md file.
Corrected "techical" to "technical" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.
=> Remove typos

README.md
[trendshift.io](https://trendshift.io/) captures the daily Github Trending data and generates a nice badge based on the highest achieved rank. This PR embeds the badge in the readme file, and hopefully, It helps to motivate contributors and attract users.
=> Add github trending badge in readme file

app/Core/Language.php, app/Domain/Auth/Services/Auth.php, app/Domain/Pageparts/Controllers/Header.php, app/Domain/Tickets/Templates/submodules/ticketDetails.sub.php, app/Domain/Users/Controllers/EditOwn.php, app/Domain/Users/Templates/editOwn.tpl.php, app/Language/en-US.ini, composer.json
Reverts Leantime/leantime#1986
=> Revert "User customizable datetime"

app/Language/ru-RU.ini
Translated button: OIDC login as via ID service
=> Added translation to ru-RU.ini

app/Core/Language.php, app/Domain/Users/Controllers/EditOwn.php, app/Language/en-US.ini
=> Caching settings results, adding timeformat to checks, adding language strings

app/Domain/Timesheets/Services/Timesheets.php
Proposed fix for issue:
https://github.com/Leantime/leantime/issues/2073
=> fix: changed logtime endpoint form using $_POST to using $params data

app/Domain/Tickets/Templates/submodules/ticketFilter.sub.php
The search term that used to be there seems to have disappeared with the design modifications, so I added it to the end of the filter.
=> Add Ticket Filter Search Term

.dev/.env, .idea/vcs.xml, app/Core/HttpKernel.php, app/Core/Language.php, app/Core/Middleware/InitialHeaders.php, app/Core/Theme.php, app/Domain/Api/Controllers/Jsonrpc.php, app/Domain/Plugins/Services/Plugins.php, app/Domain/Tickets/Services/Tickets.php
Reverts Leantime/leantime#2177
=> Revert "fix marketplace install/enable/remove/disable bugs and other misc bugs"

README.md
Added additional docker installation notes to readme, highlighting additional environment variable for use with a reverse proxy (LEAN_APP_URL)
=> Update README.md - LEAN_APP_URL

app/Language/es-ES.ini
Added missing icon to sidebar "Blueprints"
Updated translation that breaksbreaks the UI as shown in the next image (due to long text):
=> Translations updates

app/Views/Composers/App.php, app/Views/Composers/Entry.php, app/Views/Composers/Footer.php, app/Views/Composers/Header.php, app/Views/Composers/PageBottom.php, app/helpers.php
Updated code style for helpers.php and views
=> Updated code style for helper and views

app/Domain/Api/Contracts/StaticAssetType.php, app/Domain/Api/Controllers/ApiKey.php, app/Domain/Api/Controllers/Calendar.php, app/Domain/Api/Controllers/Canvas.php, app/Domain/Api/Controllers/Cpcanvas.php, app/Domain/Api/Controllers/Dbmcanvas.php, app/Domain/Api/Controllers/DelAPIKey.php, app/Domain/Api/Controllers/Eacanvas.php, app/Domain/Api/Controllers/Emcanvas.php, app/Domain/Api/Controllers/Files.php, app/Domain/Api/Controllers/Goalcanvas.php, app/Domain/Api/Controllers/I18n.php, app/Domain/Api/Controllers/Ideas.php, app/Domain/Api/Controllers/Ideation.php, app/Domain/Api/Controllers/Insightscanvas.php, app/Domain/Api/Controllers/Jsonrpc.php
This is the first part of the API classes :-) More to come later on, if this code style fixes is okay?
=> Updated code style for API classes

app/Core/HttpKernel.php, app/Core/Middleware/Auth.php, app/Domain/Cron/Controllers/Run.php, app/Domain/Menu/Repositories/Menu.php, app/Domain/Tickets/Services/Tickets.php, app/Domain/Tickets/Templates/submodules/timelineHeader.sub.php
Renaming timeline back to milestone to better represent the function of that area
=> Timeline2 milestone

app/Core/ConsoleKernel.php, app/Core/HttpKernel.php, app/Core/Language.php, app/Core/Theme.php, app/Domain/Tickets/Js/ticketsController.js
- Fix for milestone date save on table view
- Fix for theme cookie not stored 
-
=> Fix milestone dates not saved and theme settings not saved

app/Domain/Tickets/Templates/partials/subtasks.blade.php, app/Domain/Tickets/Templates/showKanban.tpl.php
=> Fixing Subtask Link not opening on same page

app/Domain/Notifications/Services/Messengers.php
=> fix error on empty status

app/Domain/Calendar/Controllers/AddEvent.php, app/Domain/Calendar/Controllers/DelEvent.php, app/Domain/Calendar/Controllers/DelExternalCalendar.php, app/Domain/Calendar/Controllers/EditEvent.php, app/Domain/Calendar/Controllers/EditExternal.php, app/Domain/Calendar/Controllers/Export.php, app/Domain/Calendar/Controllers/ExternalCal.php, app/Domain/Calendar/Controllers/Ical.php, app/Domain/Calendar/Controllers/ImportGCal.php, app/Domain/Calendar/Controllers/ShowAllGCals.php, app/Domain/Calendar/Controllers/ShowMyCalendar.php, app/Domain/Calendar/Js/calendarController.js, app/Domain/Calendar/Repositories/Calendar.php, app/Domain/Calendar/Services/Calendar.php, app/Domain/Calendar/Templates/ical.tpl.php, app/Domain/Calendar/Templates/showMyCalendar.tpl.php
Next part of the code style fixes for the Calendar namespaces :-)
=> Updated code style for calendar namespace

.github/PULL_REQUEST_TEMPLATE.md
Don't known if the project want this, but it has helped me in other open source projects to have at PR template, that automatically fill the PR description with common content.
See https://github.com/Leantime/leantime/pull/2325 for an example of this template (not a very good filled out example, but an example :-) )
=> Added PR template for easier review process

app/Views/Templates/sections/header.blade.php
View transitions allow smooth page transitions and are activated on chrome and firefox by default. Small lift for a better ui experience
=> Enable View Transitions for smooth transitions between page loads

app/Domain/Tickets/Controllers/ShowTicket.php, app/Domain/Tickets/Templates/submodules/timesheet.sub.php, app/Domain/Timesheets/Controllers/EditTime.php, app/Domain/Timesheets/Controllers/ShowAll.php, app/Domain/Timesheets/Controllers/ShowMy.php, app/Domain/Timesheets/Controllers/ShowMyList.php, app/Domain/Timesheets/Js/timesheetsController.js, app/Domain/Timesheets/Repositories/Timesheets.php, app/Domain/Timesheets/Services/Timesheets.php, app/Domain/Timesheets/Templates/editTime.tpl.php, app/Domain/Timesheets/Templates/partials/stopwatch.blade.php, app/Domain/Timesheets/Templates/showAll.tpl.php, app/Domain/Timesheets/Templates/showMy.tpl.php, app/Domain/Timesheets/Templates/showMyList.tpl.php, app/helpers.php, composer.json, composer.lock
https://github.com/Leantime/leantime/issues/2322
Look into timezone handling and the conversion of dates. 
* Switched to using carbon (https://carbon.nesbot.com)  for date handling in timesheets
* Ensure date are in UTC in all PHP code and first converted on display in UI to local timezone and format.
* Added helper to `format()` to help during transition to carbon (as this is only change in timesheets for now)
N/A
Builds on top of PR https://github.com/Leantime/leantime/pull/2354 (which have been merged by now)
=> Timesheet fixes

app/Domain/Tickets/Controllers/ShowTicket.php, app/Domain/Tickets/Templates/submodules/timesheet.sub.php, app/Domain/Timesheets/Controllers/EditTime.php, app/Domain/Timesheets/Controllers/ShowAll.php, app/Domain/Timesheets/Controllers/ShowMy.php, app/Domain/Timesheets/Controllers/ShowMyList.php, app/Domain/Timesheets/Js/timesheetsController.js, app/Domain/Timesheets/Repositories/Timesheets.php, app/Domain/Timesheets/Services/Timesheets.php, app/Domain/Timesheets/Templates/editTime.tpl.php, app/Domain/Timesheets/Templates/partials/stopwatch.blade.php, app/Domain/Timesheets/Templates/showAll.tpl.php, app/Domain/Timesheets/Templates/showMy.tpl.php, app/Domain/Timesheets/Templates/showMyList.tpl.php, app/helpers.php, composer.json, composer.lock
Reverts Leantime/leantime#2361
=> Revert "Timesheet fixes"

tests/Acceptance/CreateUserCest.php, tests/Acceptance/InstallCest.php, tests/Acceptance/LoginCest.php, tests/Acceptance/TicketsCest.php, tests/Support/Page/Acceptance/Login.php
https://github.com/Leantime/leantime/issues/2375
Ensure all acceptance tests are executed.
* Fixed namespace in `#Depends` so tests are not skipped.
N/A
N/A
=> ITKDev: Ensure that all acceptance test are executed

app/Domain/CsvImport/Templates/upload.tpl.php
(https://github.com/Leantime/leantime/issues/2401)
Quick URL update to current CSV Import documentation page.
I didn't see the test cases, the analysis suite or CI options, but happy to trigger those if needed.
=> #2401 updating csv import url

.dev/error_reporting.ini, .idea/codeception.xml, .idea/leantime-oss.iml, .idea/php.xml, .idea/phpspec.xml, .idea/phpunit.xml, app/Core/Fileupload.php, app/Core/Session.php, app/Domain/Auth/Controllers/Login.php, app/Domain/Comments/Repositories/Comments.php, app/Domain/Comments/Services/Comments.php, app/Domain/Files/Repositories/Files.php, app/Domain/Plugins/Services/Plugins.php, app/Domain/Plugins/Templates/myapps.blade.php, app/Domain/Plugins/Templates/partials/plugin.blade.php, app/Domain/Projects/Templates/showProject.tpl.php, app/Domain/Tickets/Templates/calendar.tpl.php, phpstan.neon
#2459 Fixes datetime on milestone calendar
#2455 Fixes comment datetimes
=> Fixes projectCalendar and comment dates. 

app/Command/AddUserCommand.php, app/Core/Bootloader.php, app/Core/DefaultConfig.php, app/Core/Frontcontroller.php, app/Core/HttpKernel.php, app/Core/IncomingRequest.php, app/Core/Middleware/Auth.php, app/Core/Middleware/InitialHeaders.php, app/Core/Middleware/RequestRateLimiter.php, app/Core/Middleware/TrustProxies.php, app/Domain/Plugins/Services/Plugins.php, app/Domain/Tickets/Templates/showAll.tpl.php, app/Domain/Tickets/Templates/showKanban.tpl.php, config/sample.env, webpack.mix.js
Various improvements to middle ware:
- Add ratelimiter
- Add security headers
- Escape missing escapes
- Fix plugin installer
=> Middle wareimprovements

CHANGELOG.md, app/Domain/Menu/Templates/headMenu.blade.php, app/Domain/Plugins/Controllers/Details.php, app/Domain/Plugins/Controllers/Marketplace.php, app/Domain/Plugins/Controllers/Myapps.php
#2465 
When an editor was assigned the manager role for a project (giving them the option to change project settings). They were able to see the company menu point (but not access it) 
=> Hide company menu point

CHANGELOG.md, app/Domain/Users/Controllers/DelUser.php, app/Domain/Users/Services/Users.php
#2472 
Fix for user deletion issues around project assignments
=> [fix] Delete user should remove project relationships

app/Domain/Notifications/Services/Messengers.php
[Please add a link to the GitHub issue being addressed by this change.](https://github.com/Leantime/leantime/pull/2107)
Same as in the linked pull request: upgraded Discord notification to match "Trello" or something similar with better information (such as the ToDo status)
Before:
After:
=> Improved Discord notifications

app/Domain/Tickets/Services/Tickets.php
https://github.com/Leantime/leantime/issues/2513
To save tasks/todos/tickets with the same "type"
n/a
=> 1510: "Task" changed to lowercase "task" to streamline database

app/Domain/Timesheets/Templates/showMy.tpl.php
<https://github.com/Leantime/leantime/issues/2549>
Adds links on To-Do headlines on Timesheet Week View.
Before
After
=> Added link on headline

app/Core/Application.php, app/Core/ConsoleKernel.php, app/Core/Events.php, app/Core/Providers/Cache.php, app/Core/Providers/Environment.php, app/Domain/Cron/Controllers/Run.php, app/helpers.php
=> Making laravel commands available

app/Core/Middleware/CurrentProject.php, app/Core/Middleware/StartSession.php, app/Domain/Comments/Templates/submodules/generalComment.sub.php, app/Domain/Projects/Hxcontrollers/ProjectCardProgress.php, app/Domain/Projects/Services/Projects.php, app/Domain/Projects/Templates/partials/projectCard.blade.php
Improves setting project middleware to only set project ids on main requests (not api, cron, htmx)
=> Improve current project setting flow

app/Core/HttpKernel.php, app/Core/IncomingRequest.php, app/Core/Language.php, app/Domain/Setting/Repositories/Setting.php, logs/.gitignore
=> Fix for storing language

app/Core/Middleware/Localization.php, app/Core/Support/CarbonMacros.php, app/Core/Support/DateTimeHelper.php
=> Fix localization issues for dates with translated day, month names

app/Domain/Projects/Hxcontrollers/ProjectCard.php, app/Domain/Projects/Repositories/Projects.php
Fix for broken project favorite functionality
n/a
[x] Fix
[] Feature
[] Cleanup 
=> Fix for broken project favorite function

app/Domain/Queue/Services/Queue.php, app/Domain/Queue/Workers/DefaultWorker.php, app/Domain/Queue/Workers/HttpRequestWorker.php, app/Domain/Queue/Workers/Workers.php, app/Domain/Queue/register.php
Adds a new default queue worker
n/a
[] Fix
[ x ] Feature
[] Cleanup 
=> Update queue service to include web worker

app/Domain/Goalcanvas/Templates/canvasDialog.blade.php
Adding milestone and dates back after it was removed during the last cleanup
[x] Fix
[] Feature
[] Cleanup 
=> fix the canvas dialogue

app/Core/Application.php, app/Core/DefaultConfig.php, app/Core/Providers/Cache.php, app/Core/Providers/Redis.php, app/Core/Providers/Session.php
This PR adds redis support for use in cache and sessions
#1833 
[] Fix
[x] Feature
[] Cleanup
=> Adding Redis Support for cache and sessions

app/Core/Middleware/ApiAuth.php, app/Core/Middleware/InitialHeaders.php, app/Core/Template.php, app/Domain/Api/Controllers/Jsonrpc.php, app/Domain/Api/Services/Api.php, app/Domain/Comments/Repositories/Comments.php, app/Domain/Comments/Services/Comments.php, app/Domain/Connector/Services/Connector.php, app/Domain/Goalcanvas/Repositories/Goalcanvas.php, app/Domain/Goalcanvas/Services/Goalcanvas.php, app/Domain/Ideas/Repositories/Ideas.php, app/Domain/Ideas/Services/Ideas.php, app/Domain/Projects/Repositories/Projects.php, app/Domain/Projects/Services/Projects.php, app/Domain/Tickets/Models/Tickets.php, app/Domain/Tickets/Repositories/Tickets.php, app/Domain/Tickets/Services/Tickets.php, app/Domain/Timesheets/Repositories/Timesheets.php, app/Domain/Timesheets/Services/Timesheets.php
- Allow different services within a module to be called through the jsonRPC API method calls. This is backwards compatible
- New API endpoints for polling new and updated todos, milestones, timesheets, goals, ideas, comments. 
- This enables support for our upcoming Zapier integration
This will address many integration concerns:
#239 #1985 #1507 #1500 
[x] Fix
[x] Feature
[] Cleanup
=> Api improvements

app/Core/Support/DateTimeHelper.php, app/Domain/Auth/Services/Auth.php, app/Domain/Canvas/Repositories/Canvas.php, app/Domain/Goalcanvas/Controllers/EditCanvasItem.php, app/Domain/Ideas/Controllers/IdeaDialog.php, composer.json, composer.lock
- Multiple places passed in unsupported date time formats. 
- Added a check to see if a iso8601 format was added (mostly via API) and ensure we support that. 
[x] Fix
[] Feature
[x] Cleanup
=> Various datetime bugs

.idea/leantime-oss.iml, .idea/php.xml, .idea/phpspec.xml, app/Domain/Goalcanvas/Templates/canvasComment.blade.php, app/Domain/Goalcanvas/Templates/canvasDialog.blade.php, app/Domain/Ideas/Templates/ideaDialog.tpl.php, app/Domain/Ideas/Templates/showBoards.tpl.php, public/assets/css/components/style.default.css, public/assets/css/components/wysiwyg-overrides.css
Various template clean up tasks
[] Fix
[] Feature
[x] Cleanup
=> Misc template improvements

.idea/codeception.xml, .idea/leantime-oss.iml, .idea/php.xml, .idea/phpspec.xml, app/Core/Exceptions/ExceptionHandler.php, app/Domain/Plugins/Models/MarketplacePlugin.php, app/Domain/Plugins/Services/Plugins.php
Marketplace versions were not propagated correctly. This PR fixes that
[x] Fix
[] Feature
[] Cleanup
=> Fixes to version management for plugins

CHANGELOG.md
=> Merge master

app/Domain/Tickets/Templates/partials/showTicket.blade.php, app/Views/Templates/components/navigations/tabs/content.blade.php, app/Views/Templates/components/navigations/tabs/index.blade.php, makefile
Minor fixes to tabs component.
[] Fix
[x] Feature
[] Cleanup 
=> Tabs fixes

app/Core/Bootstrap/Application.php, app/Core/Providers/Theme.php, app/Core/Theme.php, app/Domain/Menu/Repositories/Menu.php, app/Views/Templates/sections/header.blade.php, public/assets/css/components/forms.css, tests/Unit/app/Core/ThemeTest.php, tests/Unit/app/Domain/Menu/Repositories/MenuRepositoryTest.php
Fixes issues with themes and includes unit tests
#2652
[x] Fix
[] Feature
[] Cleanup
=> Fix Theme Management and write tests

app/Domain/Timesheets/Templates/partials/addTime.blade.php, app/Domain/Timesheets/Templates/partials/editTime.blade.php, app/Domain/Timesheets/Templates/showAll.blade.php, app/Views/Templates/components/forms/checkbox.blade.php, cache/installation/.gitignore, composer.lock
Replaced checkboxes in Timesheets
[] Fix
[x] Feature
[] Cleanup 
=> Timesheets module - checkbox replacement

.idea/leantime-oss.iml, .idea/phpspec.xml, app/Domain/Calendar/Controllers/Export.php, app/Domain/Calendar/Controllers/Ical.php, app/Domain/Calendar/Repositories/Calendar.php, app/Domain/Calendar/Services/Calendar.php, app/Domain/Users/Repositories/Users.php, app/Views/Templates/sections/header.blade.php, blocklist.json, package-lock.json, tests/Unit/app/Domain/Calendar/Services/CalendarServiceTest.php, tests/Unit/app/Domain/Menu/Repositories/MenuRepositoryTest.php
Fixes issues with ical export
#2644
[x] Fix
[] Feature
[] Cleanup 
=> Ical issue fix

app/Core/Middleware/InitialHeaders.php, app/Domain/Tickets/Controllers/DelTicket.php, app/Domain/Tickets/Services/Tickets.php, app/Domain/Tickets/Templates/delTicket.tpl.php, app/Domain/Timesheets/Repositories/Timesheets.php
Checks if a ticket has timesheets attached before deleting.
#2587
[x] Fix
[] Feature
[] Cleanup 
=> Check if ticket has timesheets before deleting

app/Domain/Calendar/Js/calendarController.js, app/Domain/Calendar/Templates/showMyCalendar.tpl.php
Drag and drop on my calendar was not working for tickets with due dates. (Only scheduled dates)
#2551
[x] Fix
[] Feature
[] Cleanup 
=> Fix drag and drop for due + edit dates

app/Domain/Setting/Templates/editCompanySettings.blade.php, composer.lock
Setting module checkbox replace
[] Fix
[] Feature
[] Cleanup 
=> Setting module - checkbox replacement

.idea/php.xml, app/Domain/Projects/Hxcontrollers/ProjectCardProgress.php, app/Domain/Projects/Repositories/Projects.php, app/Domain/Projects/Services/Projects.php
Project hub was showing all users having access to a project. This was updated to only show team members on the dashboard
[x] Fix
[] Feature
[] Cleanup
=> [Fix] Update project hub to only show project users who are directly assigned

app/Domain/Api/Templates/partials/apiKey.blade.php, app/Domain/Api/Templates/partials/newAPIKey.blade.php
Checkbox replacement in api module
[] Fix
[x] Feature
[] Cleanup 
=> Api module - checkbox replacement

app/Domain/Projects/Templates/partials/duplicateProject.blade.php, app/Domain/Projects/Templates/showAll.blade.php, app/Domain/Projects/Templates/showProject.blade.php
Replaced checkboxes in Projects. One pending in checklist.blade.php
[] Fix
[x] Feature
[] Cleanup 
=> Projects module - checkbox replacement

app/Domain/Projects/Templates/partials/projectCardProgressBar.blade.php, app/Views/Templates/components/elements/badge.blade.php
Badge component. replaced badge in project hub
- [ x] Feature
=> Badge component + replaced in project hub

app/Domain/Calendar/Templates/partials/addEvent.blade.php, app/Domain/Calendar/Templates/partials/editEvent.blade.php
my calendar: add+edit event flip checkbox label
=> Calendar add + edit - checkbox fix

app/Core/Providers/RouteServiceProvider.php, app/Domain/Auth/Templates/includes/loginInfo.blade.php, app/Domain/Install/Templates/new.blade.php, app/Domain/Users/Templates/editOwn.blade.php
=> Components update tracker

app/Domain/Goalcanvas/Templates/dashboard.blade.php, app/Domain/Goalcanvas/Templates/partials/goalBoard.blade.php, app/Domain/Goalcanvas/Templates/showCanvas.blade.php
=> Bug fix goal

app/Domain/Tickets/Templates/calendar.blade.php
=> buttons update in tickets calendar

app/Domain/Reports/Templates/show.blade.php, app/Views/Templates/components/elements/statistic.blade.php, app/Views/Templates/sections/footer.blade.php, public/assets/css/components/structure.css
UI fix of Reports. Also fixed the ui of Footer
=> UI fix of Reports and Footer

app/Views/Templates/components/navigations/pagination/content.blade.php, app/Views/Templates/components/navigations/pagination/index.blade.php
=> added pagination component

app/Domain/Tickets/Templates/includes/ticketFilter.blade.php
=> Bug fix dropdown filter

app/Views/Templates/components/navigations/steps/content.blade.php, app/Views/Templates/components/navigations/steps/index.blade.php
=> Added steps component

app/Language/de-DE.ini
*Added some missing translation and updated some wrong and/or incomplete translations for the formal german translation file.*
=> feat(l10n): add and update formal german translations

app/Domain/Goalcanvas/Templates/partials/canvasDialog.blade.php, app/Domain/Ideas/Controllers/IdeaDialog.php, app/Domain/Projects/Services/Projects.php, composer.lock
=> update canvas dialog input fields + idea save fix

app/Domain/Dashboard/Templates/show.blade.php, app/Domain/Reports/Templates/show.blade.php, app/Domain/Tickets/Templates/components/milestone-card.blade.php, app/Domain/Tickets/Templates/partials/milestoneCard.blade.php
Added milestone card, and fixed htmx
=> Milestone card

app/Domain/Tickets/Templates/includes/ticketFilter.blade.php, app/Domain/Tickets/Templates/showKanban.blade.php, app/Views/Templates/components/actions/dropdown/index.blade.php, public/assets/js/app/core/selects.module.mjs, public/assets/less/components/select.css
Fixed the ui bug for Filter and Group by dropdown. Made changes to Choices CSS
=> Filter and Group By dropdown UI fix

app/Domain/Comments/Js/commentsController.js, app/Domain/Comments/Templates/components/single-comment.blade.php, app/Domain/Dashboard/Controllers/Show.php, app/Domain/Dashboard/Hxcontrollers/ProjectUpdates.php, app/Domain/Dashboard/Js/dashboardController.js, app/Domain/Dashboard/Templates/components/project-status-comment.blade.php, app/Domain/Dashboard/Templates/components/project-update-form.blade.php, app/Domain/Dashboard/Templates/components/project-updates.blade.php, app/Domain/Dashboard/Templates/show.blade.php, app/Domain/Menu/Templates/menu.blade.php, app/Views/Templates/components/forms/reset-button.blade.php, app/Views/Templates/layouts/app.blade.php, makefile, public/assets/js/app/app-new.js, public/assets/js/app/htmx.js
=> Hx boost, hx error handling

app/Domain/Comments/Js/commentsController.js, app/Domain/Comments/Templates/components/single-comment.blade.php, app/Domain/Dashboard/Controllers/Show.php, app/Domain/Dashboard/Hxcontrollers/ProjectUpdates.php, app/Domain/Dashboard/Js/dashboardController.js, app/Domain/Dashboard/Templates/components/project-status-comment.blade.php, app/Domain/Dashboard/Templates/components/project-update-form.blade.php, app/Domain/Dashboard/Templates/components/project-updates.blade.php, app/Domain/Dashboard/Templates/show.blade.php, app/Views/Templates/components/forms/reset-button.blade.php, makefile
=> Project status

app/Domain/Ldap/Services/Ldap.php
Wrong call to debug facade in ldap servce
=> Ldap debug fix

app/Domain/Tickets/Templates/calendar.tpl.php
Milestone calendar header fix
#2798
=> Fixes wrong dates in milestone calendar header

app/Domain/Projects/Services/Projects.php
=> Update Project Notification Event

app/Domain/Users/Templates/editOwn.blade.php, app/Views/Templates/components/forms/select/index.blade.php, public/assets/css/components/style.default.css
=> Edit own update

app/Domain/Widgets/Templates/components/moveableWidget.blade.php, app/Domain/Widgets/Templates/partials/welcome.blade.php, public/assets/less/components/select.css
Alignment on widgets, headline spacing, dropdown component replaced and script added
Ticket #2221, 2224, 2225
=> Dashboard page widgets UI and dropdown fix

app/Domain/Projects/Hxcontrollers/ProjectCard.php, app/Domain/Projects/Hxcontrollers/ProjectHubProjects.php, app/Domain/Projects/Templates/partials/projectHubProjects.blade.php, app/Domain/Projects/Templates/projectHub.blade.php, app/Views/Templates/components/forms/button.blade.php
dropdown issue, favorite select, button sizing fix
#2227, 2228, 2229
=> Project hub fix

app/Domain/Tickets/Templates/components/milestone-dropdown.blade.php, app/Domain/Tickets/Templates/components/ticket-column-card.blade.php, app/Views/Templates/components/actions/dropdown/index.blade.php
=> Selectable dropdown

app/Domain/Users/Templates/showAll.blade.php, app/Views/Templates/components/forms/button.blade.php
=> User management fix

app/Views/Templates/components/forms/text-editor.blade.php
=> update the script for editor to load the module properly

app/Domain/Goalcanvas/Templates/components/canvas.blade.php, app/Domain/Goalcanvas/Templates/components/goal-item-card.blade.php, app/Domain/Goalcanvas/Templates/dashboard.blade.php, app/Domain/Goalcanvas/Templates/partials/bigRockDialog.blade.php, app/Domain/Goalcanvas/Templates/partials/canvasDialog.blade.php, app/Domain/Tickets/Controllers/EditMilestone.php, app/Domain/Tickets/Templates/includes/ticketFilter.blade.php, app/Domain/Tickets/Templates/includes/ticketNewBtn.blade.php, app/Domain/Tickets/Templates/partials/milestoneDialog.blade.php, app/Domain/Tickets/Templates/roadmap.blade.php, app/Domain/Tickets/Templates/showKanban.blade.php, app/Views/Templates/components/content/context-menu.blade.php
=> Goal bug fixes

app/Domain/Calendar/Templates/showMyCalendar.blade.php, app/Views/Templates/components/forms/button.blade.php
=> My Calendar fix

app/Domain/Tickets/Templates/calendar.blade.php, app/Domain/Tickets/Templates/roadmap.blade.php, app/Views/Templates/components/forms/button.blade.php
timeline and calendar not showing fixed; button 
=> Milestone timeline and calendar fix

app/Domain/Menu/Templates/partials/projectselector/projectSelector.blade.php, public/assets/less/components/cards.css, public/assets/less/components/nav.css, public/assets/less/components/tabs.css
=> tab and nav size issues

public/assets/css/components/structure.css, public/assets/less/components/nav.css
=> nav height

app/Domain/Clients/Controllers/NewClient.php, app/Domain/Clients/Templates/newClient.blade.php, app/Domain/Clients/Templates/showAll.blade.php
fixed modal issue and button sizing
=> All Clients fixes

app/Domain/Comments/Js/commentsComponent.js, app/Domain/Comments/Templates/components/single-comment.blade.php, app/Domain/Comments/Templates/partials/commentList.blade.php, app/Domain/Dashboard/Templates/components/project-updates.blade.php, app/Domain/Tickets/Templates/partials/subtasks.blade.php, app/Domain/Tickets/Templates/showKanban.blade.php, app/Views/Templates/components/content/context-menu.blade.php, public/assets/css/components/kanban.css
=> ui commetn fixes

app/Domain/Goalcanvas/Controllers/Dashboard.php, app/Domain/Goalcanvas/Templates/components/canvas.blade.php, app/Domain/Goalcanvas/Templates/components/goal-item-card.blade.php, app/Domain/Goalcanvas/Templates/partials/canvasDialog.blade.php, app/Domain/Tickets/Templates/components/milestone-dropdown.blade.php, public/assets/js/app/componentManager/SelectManager.mjs, public/assets/js/app/components/datePickers.module.mjs
=> Goal update

app/Domain/Tickets/Hxcontrollers/TicketColumn.php, app/Domain/Tickets/Templates/includes/ticketFilterHx.blade.php, app/Domain/Tickets/Templates/showKanban.blade.php
=> tickets filter

app/Domain/Calendar/Js/calendarController.mjs, app/Domain/Tickets/Js/ticketsController.js, app/Domain/Tickets/Templates/calendar.blade.php, public/assets/css/components/gantt-overwrites.css
milestone calendar fix and timeline gantt ui fix
=> Milestone calendar and UI fixes

app/Domain/Comments/Services/Comments.php, app/Domain/Dashboard/Hxcontrollers/ProjectUpdates.php, app/Domain/Dashboard/Templates/components/project-status-comment.blade.php, app/Domain/Dashboard/Templates/components/project-updates.blade.php, app/Domain/Tickets/Templates/includes/ticketFilterHx.blade.php
=> Project reply

app/Domain/Tickets/Templates/components/priority-select.blade.php, app/Domain/Tickets/Templates/components/ticket-column-card.blade.php, app/Domain/Tickets/Templates/components/ticket-column.blade.php, app/Domain/Tickets/Templates/includes/ticketFilter.blade.php, app/Domain/Tickets/Templates/includes/ticketFilterHx.blade.php, app/Domain/Tickets/Templates/showKanban.blade.php
=> Htmx search

app/Domain/Dashboard/Templates/components/project-status-comment.blade.php, app/Domain/Goalcanvas/Hxcontrollers/Canvas.php, app/Domain/Goalcanvas/Templates/components/canvas.blade.php, app/Domain/Goalcanvas/Templates/components/goal-item-card.blade.php, app/Domain/Goalcanvas/Templates/dashboard.blade.php, app/Domain/Menu/Templates/partials/leftnav/submenu.blade.php, app/Domain/Tickets/Templates/components/ticket-column.blade.php, app/Domain/Tickets/Templates/includes/ticketFilter.blade.php, app/Views/Templates/components/elements/loadingText.blade.php
=> Tix skeleton project replies UI fix

app/Domain/Clients/Js/clientsController.js, app/Domain/Clients/Templates/showAll.blade.php, app/Domain/Clients/Templates/showClient.blade.php, app/Domain/Dashboard/Templates/show.blade.php, app/Domain/Projects/Templates/includes/projectDetails.blade.php, app/Domain/Projects/Templates/showProject.blade.php
=> Client access issues fix

app/Domain/Menu/Templates/headMenu.blade.php, app/Domain/Notifications/Templates/partials/latestNews.blade.php, app/Domain/Widgets/Js/widgetController.js, app/Domain/Widgets/Templates/components/moveableWidget.blade.php
update and notification dropdown fix
=> Notification dropdown fix

app/Domain/Canvas/Controllers/BoardDialog.php, app/Domain/Canvas/Templates/partials/boardDialog.blade.php, app/Domain/Canvas/Templates/showCanvasBottom.blade.php, app/Domain/Canvas/Templates/showCanvasTop.blade.php, app/Domain/Cpcanvas/Templates/showCanvas.blade.php, app/Domain/Dbmcanvas/Templates/showCanvas.blade.php, app/Domain/Eacanvas/Templates/showCanvas.blade.php, app/Domain/Emcanvas/Templates/showCanvas.blade.php, app/Domain/Insightscanvas/Templates/showCanvas.blade.php, app/Domain/Lbmcanvas/Templates/showCanvas.blade.php, app/Domain/Leancanvas/Templates/partials/boardDialog.blade.php, app/Domain/Leancanvas/Templates/showCanvas.blade.php, app/Domain/Minempathycanvas/Templates/showCanvas.blade.php, app/Domain/Obmcanvas/Templates/showCanvas.blade.php, app/Domain/Retroscanvas/Templates/showCanvas.blade.php, app/Domain/Riskscanvas/Templates/showCanvas.blade.php, app/Domain/Sbcanvas/Templates/showCanvas.blade.php, app/Domain/Smcanvas/Templates/showCanvas.blade.php, app/Domain/Sqcanvas/Templates/showCanvas.blade.php, app/Domain/Swotcanvas/Templates/showCanvas.blade.php, app/Domain/Valuecanvas/Templates/showCanvas.blade.php
=> Leancanvas fix

app/Domain/Tickets/Js/ticketsController.js, app/Domain/Tickets/Templates/components/cards/ticket-card.blade.php, app/Views/Templates/components/content/card/index.blade.php
=> fixed the issue with moving the tickets

app/Domain/Setting/Templates/editCompanySettings.blade.php
Tabs replaced, button ui and logo upload fix
=> Company Settings fixes

app/Domain/Projects/Js/projectsController.js, app/Domain/Projects/Templates/delProject.blade.php, app/Domain/Projects/Templates/includes/projectDetails.blade.php, app/Domain/Projects/Templates/partials/duplicateProject.blade.php, app/Domain/Projects/Templates/showProject.blade.php
Tabs fixed, datepicker and module script fixed
=> Project settings fix

app/Domain/Api/Controllers/Projects.php, app/Domain/Dashboard/Controllers/Home.php, app/Domain/Projects/Controllers/DuplicateProject.php, app/Domain/Projects/Js/projectsController.js, app/Domain/Projects/Services/Projects.php, app/Domain/Tickets/Controllers/Roadmap.php, app/Domain/Tickets/Js/ticketsController.js, app/Domain/Tickets/Repositories/Tickets.php, app/Domain/Tickets/Services/Tickets.php, app/Domain/Tickets/Templates/roadmap.tpl.php, app/Domain/Widgets/Hxcontrollers/Welcome.php, public/assets/css/components/gantt-overwrites.css, public/assets/css/libs/frappe_theme.css, public/assets/js/libs/simpleGantt/frappe-gantt.js
**Title:** feat: improve roadmap date handling and milestone retrieval
**Description**
This pull request introduces significant enhancements to the roadmap's date handling and milestone retrieval processes. The key changes include:
- **Refactored Date Handling:** The roadmap template has been updated to utilize a helper function for validating dates, improving the reliability of date-related operations.
- **Dynamic Project Fetching:** The Tickets service now fetches assigned projects dynamically, ensuring that the data is always up-to-date and relevant.
- **Enhanced Milestone Retrieval:** Milestones are now sorted hierarchically, and a new private method has been added to build a ticket tree structure. This enhancement not only improves the organization of milestones but also increases …
=> feat: improve roadmap date handling and milestone retrieval

app/Domain/Tickets/Templates/components/ticket-column.blade.php
=> added id to moveable cards

app/Domain/Tickets/Controllers/ShowAll.php
=> Fix show all tickets table

public/assets/css/components/nav.css
=> fix nav selection

app/Domain/Tickets/Templates/includes/ticketFilter.blade.php, app/Views/Templates/components/actions/dropdown/index.blade.php
=> Filter Dropdown ui fix

app/Domain/Dashboard/Controllers/Show.php, app/Domain/Goalcanvas/Templates/components/chips/status-select.blade.php, app/Domain/Tickets/Controllers/ShowAll.php, app/Domain/Tickets/Controllers/ShowList.php, app/Domain/Tickets/Hxcontrollers/ShowKanban.php, app/Domain/Tickets/Hxcontrollers/TicketCard.php, app/Domain/Tickets/Services/Tickets.php, app/Domain/Tickets/Templates/components/chips/milestone-select.blade.php, app/Domain/Tickets/Templates/components/ticket-column.blade.php, public/assets/css/components/nav.css
=> Cached repeated calls

app/Language/en-US.ini, public/theme/default/css/dark.css, public/theme/minimal/css/dark.css
=> fix: firefox design issue

app/Domain/Tickets/Services/Tickets.php, app/Domain/TwoFA/Controllers/Edit.php
Applies coding standards to PHP code. 
Follows up on https://github.com/Leantime/leantime/pull/3066.
=> Applied coding standards
